/**
 * Shared Anthropic call surface for SUB-AGENT execution paths.
 *
 * Why this exists: PTC (programmatic tool calling) was being half-implemented
 * in several hand-rolled `fetch('…/v1/messages')` loops (the delegate_to_agent
 * worker loop, the agent-tick lane loop). Each set the beta header or sent
 * tools that opted into PTC via `allowed_callers` WITHOUT adding the
 * code_execution tool and threading `container_id` across iterations, so they
 * 400'd with "container_id is required when there are pending tool uses
 * generated by code execution with tools." As clients spin up more agents,
 * every duplicated call site is a chance to reintroduce that class of bug.
 *
 * This module centralizes the two things sub-agents need:
 *   - callAnthropicJSON: one raw POST with consistent headers + error capture.
 *   - runAgentToolLoop: a bounded tool loop where PTC is handled correctly in
 *     ONE place. enablePtc defaults to false → strip `allowed_callers` and call
 *     tools directly (the right default for bounded sub-agent tasks). When a
 *     path genuinely wants PTC, set enablePtc:true and the loop adds the
 *     code_execution tool, sends the beta header, and threads the container.
 *
 * NOTE: the main iris-brain callAnthropic loop is intentionally NOT routed
 * through here — it carries the gate/trace/thinking machinery and is its own
 * concern. This module is for the sub-agent paths.
 */

const ANTHROPIC_URL = 'https://api.anthropic.com/v1/messages';
const PTC_BETA_HEADER = 'advanced-tool-use-2025-11-20';
const PTC_CALLER = 'code_execution_20250825';

export interface AnthropicCallResult {
  ok: boolean;
  status: number;
  json: any;
  rawBody: string;
}

/** One POST to the Messages API with consistent headers + non-throwing error capture. */
export async function callAnthropicJSON(
  apiKey: string,
  body: any,
  opts?: { betaHeader?: string },
): Promise<AnthropicCallResult> {
  const headers: Record<string, string> = {
    'x-api-key': apiKey,
    'anthropic-version': '2023-06-01',
    'content-type': 'application/json',
  };
  if (opts?.betaHeader) headers['anthropic-beta'] = opts.betaHeader;
  const res = await fetch(ANTHROPIC_URL, { method: 'POST', headers, body: JSON.stringify(body) });
  const rawBody = await res.text();
  let json: any = null;
  try { json = rawBody ? JSON.parse(rawBody) : null; } catch { /* leave json null */ }
  return { ok: res.ok, status: res.status, json, rawBody };
}

export interface AgentToolLoopParams {
  apiKey: string;
  model: string;
  /** System prompt text (cached as a single ephemeral block). */
  system: string;
  /** First user turn that kicks off the loop. */
  initialMessage: string;
  tools?: any[];
  /** Max tool-use round-trips before we stop looping. */
  maxIterations: number;
  maxTokens: number;
  /** Connections + user context handed to executeTool for each tool call. */
  connections: any[];
  userContext: any;
  /**
   * PTC opt-in. Default false: strip `allowed_callers` so the model calls
   * tools directly (no code-exec container). true: add the code_execution
   * tool, send the beta header, and thread container_id across iterations.
   */
  enablePtc?: boolean;
}

export interface AgentToolLoopResult {
  finalText: string;
  toolsUsed: string[];
  tokensIn: number;
  tokensOut: number;
  cacheRead: number;
  stopReason: string | null;
  /** Non-null when a request returned non-2xx. Caller decides how to surface it. */
  apiError: { status: number; rawBody: string } | null;
}

/**
 * Run a bounded Anthropic tool loop for a sub-agent. PTC is handled here so
 * no caller has to (and can't get it half-right). Returns the final text plus
 * usage; on an API error it returns early with `apiError` set rather than
 * throwing, so callers can produce their own honest failure message.
 */
export async function runAgentToolLoop(p: AgentToolLoopParams): Promise<AgentToolLoopResult> {
  const enablePtc = p.enablePtc ?? false;
  const baseTools = p.tools ?? [];
  const hasTools = baseTools.length > 0;

  // PTC decision in ONE place.
  let usePtc = false;
  let toolsForRequest = baseTools;
  if (hasTools) {
    if (enablePtc) {
      usePtc = baseTools.some(
        (t) => Array.isArray(t.allowed_callers) && t.allowed_callers.includes(PTC_CALLER),
      );
      if (usePtc) {
        const { CODE_EXECUTION_TOOL } = await import('../webhooks/whatsapp/agent-tools');
        toolsForRequest = [...baseTools, CODE_EXECUTION_TOOL];
      }
    } else {
      // Force direct tool calling: strip allowed_callers so the API doesn't
      // try to run code execution (which would require container threading).
      toolsForRequest = baseTools.map((t) => {
        if (Array.isArray(t?.allowed_callers)) {
          const { allowed_callers: _drop, ...rest } = t;
          return rest;
        }
        return t;
      });
    }
  }

  let executeTool: any = null;
  if (hasTools) {
    const at = await import('../webhooks/whatsapp/agent-tools');
    executeTool = at.executeTool;
  }

  const messages: any[] = [{ role: 'user', content: p.initialMessage }];
  const toolsUsed: string[] = [];
  let tokensIn = 0;
  let tokensOut = 0;
  let cacheRead = 0;
  let finalText = '';
  let stopReason: string | null = null;
  let containerId: string | null = null;

  let iter = 0;
  while (iter < p.maxIterations) {
    iter++;
    const body: any = {
      model: p.model,
      max_tokens: p.maxTokens,
      system: [{ type: 'text', text: p.system, cache_control: { type: 'ephemeral' } }],
      messages,
    };
    if (hasTools) {
      body.tools = toolsForRequest.map((t, i) =>
        i === toolsForRequest.length - 1 ? { ...t, cache_control: { type: 'ephemeral' } } : t,
      );
    }
    // Container only travels with a PTC request (the whole reason the old
    // hand-rolled loops 400'd was passing/omitting it inconsistently).
    if (usePtc && containerId) body.container = containerId;

    const r = await callAnthropicJSON(p.apiKey, body, usePtc ? { betaHeader: PTC_BETA_HEADER } : undefined);
    if (!r.ok) {
      return { finalText, toolsUsed, tokensIn, tokensOut, cacheRead, stopReason, apiError: { status: r.status, rawBody: r.rawBody } };
    }
    const data = r.json;
    tokensIn += data?.usage?.input_tokens ?? 0;
    tokensOut += data?.usage?.output_tokens ?? 0;
    cacheRead += data?.usage?.cache_read_input_tokens ?? 0;
    if (data?.container?.id) containerId = data.container.id;
    stopReason = data?.stop_reason ?? null;

    const content = data?.content ?? [];
    const textBlocks = content.filter((b: any) => b.type === 'text');
    if (textBlocks.length > 0) finalText = textBlocks.map((b: any) => b.text).join('\n').trim();

    const toolUseBlocks = content.filter((b: any) => b.type === 'tool_use');
    if (stopReason !== 'tool_use' || !hasTools || !executeTool || toolUseBlocks.length === 0) break;

    messages.push({ role: 'assistant', content });
    const toolResults: any[] = [];
    for (const block of toolUseBlocks) {
      toolsUsed.push(block.name);
      try {
        const result = await executeTool({ name: block.name, input: block.input }, p.connections, p.userContext);
        toolResults.push({
          type: 'tool_result',
          tool_use_id: block.id,
          content: result.content ?? '',
          is_error: !result.success,
        });
      } catch (err: any) {
        toolResults.push({
          type: 'tool_result',
          tool_use_id: block.id,
          content: `Tool error: ${err?.message ?? String(err)}`,
          is_error: true,
        });
      }
    }
    messages.push({ role: 'user', content: toolResults });
  }

  return { finalText, toolsUsed, tokensIn, tokensOut, cacheRead, stopReason, apiError: null };
}
